=== leadware/drools-server/drools-server-model/src/main/resources/xsd/drools-server-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
		targetNamespace="http://www.leadware.net/drools-server-configuration" 
		xmlns:tns="http://www.leadware.net/drools-server-configuration" 
		elementFormDefault="qualified">
	<!--
	  #%L
	  drools-server
	  $Id:$
	  $HeadURL:$
	  %%
	  Copyright (C) 2013 Leadware
	  %%
	  Licensed under the Apache License, Version 2.0 (the "License");
	  you may not use this file except in compliance with the License.
	  You may obtain a copy of the License at
	  
	       http://www.apache.org/licenses/LICENSE-2.0
	  
	  Unless required by applicable law or agreed to in writing, software
	  distributed under the License is distributed on an "AS IS" BASIS,
	  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	  See the License for the specific language governing permissions and
	  limitations under the License.
	  #L%
  	-->
  	
	<!-- Type de ressources -->
	<simpleType name="ResourceTypeConfiguration">
		<restriction base="string">
			<enumeration value="DRL" />
			<enumeration value="XDRL" />
			<enumeration value="DSL" />
			<enumeration value="DSLR" />
			<enumeration value="DRF" />
			<enumeration value="DTABLE" />
			<enumeration value="BRL" />
			<enumeration value="PKG" />
			<enumeration value="PMML" />
			<enumeration value="XSD" />
			<enumeration value="DESCR" />
			<enumeration value="CHANGE_SET" />
			<enumeration value="BPMN" />
		</restriction>
	</simpleType>
	
	<!-- Severite des resultats -->
	<simpleType name="ResultSeverityConfiguration">
		<restriction base="string">
			<enumeration value="ERROR" />
			<enumeration value="INFO" />
			<enumeration value="WARN" />
		</restriction>
	</simpleType>
	
	<!-- Type de session intelligente -->
	<simpleType name="KnowledgeSessionTypeConfiguration">
		<restriction base="string">
			<enumeration value="STATELESS" />
			<enumeration value="STATEFUL" />
		</restriction>
	</simpleType>
	
	<!-- Configuration d'un chemin de classe -->
	<complexType name="ClasspathConfiguration">
		<attribute name="url" type="string" use="optional" default="." />
	</complexType>
	
	<!-- Configuration de la liste des classpaths -->
	<complexType name="ClassPathsConfiguration">
		<sequence>
			<element name="url" type="tns:ClasspathConfiguration" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	
	<!-- Ressource -->
	<complexType name="ResourceConfiguration">
		<attribute name="name" type="string" use="required" />
		<attribute name="type" type="tns:ResourceTypeConfiguration" use="optional" default="DRL" />
		<attribute name="inClassPath" type="boolean" use="optional" default="true" />
		<attribute name="path" type="string" use="required" />
	</complexType>
	
	<!-- Ressource Ref -->
	<complexType name="ResourceConfigurationRef">
		<attribute name="resource-name" type="string" use="required" />
	</complexType>
	
	<!-- Ressources -->
	<complexType name="ResourcesConfiguration">
		<sequence>
			<element name="resource" type="tns:ResourceConfiguration" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	
	<!-- Base de connaissance -->
	<complexType name="KnowledgeBaseConfiguration">
		<sequence>
			<element name="resource-ref" type="tns:ResourceConfigurationRef" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
		<attribute name="name" type="string" use="required" />
		<attribute name="onDuplicateRule" type="tns:ResultSeverityConfiguration" use="optional" default="INFO" />
		<attribute name="onDuplicateFunction" type="tns:ResultSeverityConfiguration" use="optional" default="INFO" />
		<attribute name="multiThreadEvaluation" type="boolean" use="optional" default="false" />
		<attribute name="maxEvaluationThreads" type="int" use="optional" default="3" />
	</complexType>
	
	<!-- Bases de connaissance -->
	<complexType name="KnowledgeBasesConfiguration">
		<sequence>
			<element name="knowledge-base" type="tns:KnowledgeBaseConfiguration" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	
	<!-- Configuration de referencement d'une base de connaissance -->
	<complexType name="KnowledgeBaseConfigurationRef">
		<attribute name="knowledge-base" type="string" use="required" />
	</complexType>
	
	<!-- Agent intelligent -->
	<complexType name="KnowledgeAgentConfiguration">
		<sequence>
			<element name="knowledge-base-ref" type="tns:KnowledgeBaseConfigurationRef" minOccurs="1" maxOccurs="1" />
		</sequence>
		<attribute name="name" type="string" use="required" />
		<attribute name="newInstance" type="boolean" fixed="false" />
		<attribute name="scanDirectories" type="boolean" use="optional" default="true" />
		<attribute name="scanResources" type="boolean" use="optional" default="true" />
		<attribute name="scanPeriod" type="unsignedShort" use="optional" default="60" />
	</complexType>
	
	<!-- Agents intelligent -->
	<complexType name="KnowledgeAgentsConfiguration">
		<sequence>
			<element name="knowledge-agent" type="tns:KnowledgeAgentConfiguration" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	
	<!-- Configuration de referencement d'un Agent -->
	<complexType name="KnowledgeAgentConfigurationRef">
		<attribute name="knowledge-agent" type="string" use="required" />
	</complexType>
	
	<!-- Session intelligente -->
	<complexType name="KnowledgeSessionConfiguration">
		<choice>
			<element name="knowledge-base-ref" type="tns:KnowledgeBaseConfigurationRef" minOccurs="1" maxOccurs="1" />
			<element name="knowledge-agent-ref" type="tns:KnowledgeAgentConfigurationRef" minOccurs="1" maxOccurs="1"/>
		</choice>
		<attribute name="name" type="string" use="required" />
		<attribute name="type" type="tns:KnowledgeSessionTypeConfiguration" use="optional" default="STATELESS" />
		<attribute name="debug" type="boolean" use="optional" default="false" />
	</complexType>
	
	<!-- Sessions intelligente -->
	<complexType name="KnowledgeSessionsConfiguration">
		<sequence>
			<element name="knowledge-session" type="tns:KnowledgeSessionConfiguration" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>
	
	<!-- Drools server configuration -->
	<complexType name="DroolsServerConfiguration">
		<sequence>
			<element name="classpaths" type="tns:ClassPathsConfiguration" minOccurs="0" maxOccurs="1"/>
			<element name="resources" type="tns:ResourcesConfiguration" minOccurs="1" maxOccurs="1"/>
			<element name="knowledge-bases" type="tns:KnowledgeBasesConfiguration" minOccurs="1" maxOccurs="1"/>
			<element name="knowledge-agents" type="tns:KnowledgeAgentsConfiguration" minOccurs="0" maxOccurs="1"/>
			<element name="knowledge-sessions" type="tns:KnowledgeSessionsConfiguration" minOccurs="0" maxOccurs="1" />
		</sequence>
	</complexType>
	
	<!-- Drools Server Root Element -->
	<element name="drools-server" type="tns:DroolsServerConfiguration">
		<unique name="uniqueSessionName">
			<selector xpath="tns:knowledge-sessions/tns:knowledge-session" />
			<field xpath="@name" />
		</unique>
		<unique name="uniqueAgentName">
			<selector xpath="tns:knowledge-agents/tns:knowledge-agent" />
			<field xpath="@name" />
		</unique>
		<unique name="uniqueResourceName">
			<selector xpath="tns:resources/tns:resource" />
			<field xpath="@name" />
		</unique>
		<unique name="uniqueBaseName">
			<selector xpath="tns:knowledge-bases/tns:knowledge-base" />
			<field xpath="@name" />
		</unique>
	</element>
	
</schema>

=== leadware/drools-server/drools-server-model/src/test/resources/META-INF/drools-server-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  #%L
  DROOLS SERVER :: Model
  $Id:$
  $HeadURL:$
  %%
  Copyright (C) 2013 Leadware
  %%
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  #L%
  -->

<drools-server xmlns="http://www.example.org/drools-server-configuration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/drools-server-configuration ../../../main/resources/xsd/drools-server-configuration.xsd ">
	
	<!--
	  Copyright [2013] - 24/12/2013 by Leadware.
	
	  Licensed under the Apache License, Version 2.0 (the "License");
	  you may not use this file except in compliance with the License.
	  You may obtain a copy of the License at
	
	      http://www.apache.org/licenses/LICENSE-2.0
	
	  Unless required by applicable law or agreed to in writing, software
	  distributed under the License is distributed on an "AS IS" BASIS,
	  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	  See the License for the specific language governing permissions and
	  limitations under the License.
	
	  $24/12/2013$
  	-->
  	
	<knowledge-session name="ksession1" type="STATELESS">
		<knowledge-agent name="my-agent" >
			<resource path="" type="DRL"/>
			<resource path="" type="CHANGE_SET"/>
			<resource path="" type="XSD"/>
		</knowledge-agent>
	</knowledge-session>
	<knowledge-session name="ksession2" type="STATEFUL">
		<knowledge-base>
			<resource path="" inClassPath="false" type="DRL"/>
		</knowledge-base>
	</knowledge-session>
</drools-server>
